### ISSUE TITLE
You can't use the LGPL license if you link with the Itext5 library

### ISSUE THREAD

**Issue by borgogelli** [opensagres/xdocreport#121]
Hello

I think you can't release that project with the LGPL license If you link the itex5 library with your code.

Regards

Andrea

**Comment by angelozerr** [comment]
@pascalleclercq could you answer to this issue please. Thanks!

**Comment by pascalleclercq** [comment]
Hi,

xdocreport code is licensed under MIT license.

We don't provide iText3 not iText5 in our core, It's just a maven transitive dependency.

Our sample are licensed under LGPL license because we need iText3, see : 
https://github.com/opensagres/xdocreport.samples/blob/master/license.txt

We don't provide any sample based on iText5, thus we don't need to comply with AGPL license.

**Comment by borgogelli** [comment]
Thank you for the clarification
