### ISSUE TITLE
Jodconverter 3.0 with Xdocreport has implemented

### ISSUE THREAD

**Issue by abdoah77** [opensagres/xdocreport#153]
Hi Angelo,
Finally, I have implemented Jodconverter 3.0 with Xdocreport 

thank you.

**Comment by angelozerr** [comment]
@abdoah77 why do you create a new issue although it's the same than https://github.com/opensagres/xdocreport/issues/152?

It should be cool if you could do a PR. Several people waits this converter, but I have never find time to do that.

I close this issue because it's the same than https://github.com/opensagres/xdocreport/issues/153
