### ISSUE TITLE
How to format a date type value in a velocity template ?

### ISSUE THREAD

**Issue by mickaelbaron** [opensagres/xdocreport#29]
Hi,

I would like to choose the format of date value into the velocity template. Here is a simple example.

I've a model Person with an attribute of date type (i.e Date birthday).

```
public class Person {
Date birthday
}
```

In my context i give the instance of my Person 

```
IContext context = report.createContext();
context.put("incoming", refModel);
```

Into my Word document, actually i have this template content
```
$incoming.birthday
```

But the result is not "user friendly". Do you have an idea to format directly my date value into the velocity template ? I don't want to add a specific value into the context with the right format value of my date...

Thanks

Mickael

**Comment by angelozerr** [comment]
@mickaelbaron your issue is about Velocity template engien uses. To be honnest with you I have never played with date & Velocity. You can find a sample at http://www.java2s.com/Code/Java/Velocity/HowtouseDateinVelocity.htm

IMHO I think it's a bad idea to format date inside docx template, because mergefield write is more complex.

**Comment by mickaelbaron** [comment]
Hi Angelo,

Thanks for your response. You're right is about a Velocity template comment => off topic, sorry.

I don't think is a bad idea to format date inside the Velocity template. In fact, this aspect concerns the UI layer and it's the purpose of a template, isn't it ?

Any way, for my problem, here is my solution

A declare a DateTool instance
```
context.put("date", new DateTool());
```

DateTool is a class from Velocity-tools-x.x.jar. You need to add this dependency into your pom.xml.

Into the Velocity template (in fact the docx template), i change for that
```
$date.format("dd-MM-yyyy", $incoming.birthday)
````

Mickael

**Comment by angelozerr** [comment]
> I don't think is a bad idea to format date inside the Velocity template. In fact, this aspect concerns the UI layer and it's the purpose of a template, isn't it ?

I agree with you, docx template is the UI Layer. When you use Velocity to generate HTML, I agree with you, date must be formatted inside the template. In this case, the HTML template is written by a developer.

But in the case of docx template, I think formatting must be done not inside docx template because :

 * template can be created by a non developer (like secratary), so field name must be simple.
 * when mergefield is too long, MS Word doesnt displays the full name of the mergefield. So it's a little hard to read the field name.
 * the XDocReport Macro https://code.google.com/p/xdocreport/wiki/DocxDesignReportMacro works with simple field name.
