### ISSUE TITLE
When can we expect 2.0.3 to be released?

### ISSUE THREAD

**Issue by esuomi** [opensagres/xdocreport#361]
The POI version change in 2.0.3 (#352) is quite important to our team so we'd like to collectively know when we can expect it to be released officially.

Thanks :)

**Comment by yhorndt** [comment]
Same here, we rely on POI 4.0.1 for other implementations and cannot use the current version of xdocreport for this reason.

**Comment by esuomi** [comment]
@pascalleclercq Any update on this?

**Comment by esuomi** [comment]
@angelozerr You seem to be active in this repo, do you have any estimate for this? It's getting _really_ late for such point release...

**Comment by angelozerr** [comment]
@esuomi to be honest with you, I don't know. I understand your frustration, but I try to maintain XDocReport in my so little spare time by reviewing PR but it should be very fantastic to have more active contributors.

I think before creating a new release we should fix the build which fails https://travis-ci.org/opensagres/xdocreport/jobs/610037102#L2560

We should replace MimetypesFileTypeMap by a custom code (to support any JDK because it seems JDK 11 removes MimetypesFileTypeMap), but I have no time to do that.

Once this issue will be fixed I hope @pascalleclercq will have time to create a new release.

**Comment by angelozerr** [comment]
2.0.3 has been released. Thanks so much @pascalleclercq !
