### ISSUE TITLE
xdocReport docx to pdf status

### ISSUE THREAD

**Issue by hendorog** [opensagres/xdocreport#81]
Is there any documentation to give an indication of what works and what is yet to be implemented?

I tried to use xdocReport to populate a docx and then convert to a PDF.
I found the population of the docx worked well and I would consider it usable.

Conversely the PDF generation was not usable. The docx contained images positioned relative to the page (i.e. absolute positioning). The converter produces a pdf with those images offset vertically by large amounts. Maybe it's OK for very simple text only PDF's though?

It would be nice to have a list showing what needs to be improved and what is considered working.

**Comment by angelozerr** [comment]
> Is there any documentation to give an indication of what works and what is yet to be implemented?

No because docx->PDF converter is the very hard task of XDocReport and there are so a lot of cases that it's difficult to list the limitation of the converter. We try to improve in each version. But if you don't like XDocReport converter you can use an other if you wish.

To improve the converter, please create a little issue per problem with a simple docx to try to fix it. Thanks.

**Comment by hendorog** [comment]
OK thanks, I will create a sample. 

Is the wiki editable? If so I can create a page where people can add known working samples if they wish. 

There seem to be limited other options in this space - at least at a reasonable price. I'm currently looking at cloudconvert.com, which does a good job converting my sample, but is very slow.

**Comment by angelozerr** [comment]
> Is the wiki editable

Yes. I didn't remember but yiu can add your limitation at https://github.com/opensagres/xdocreport/wiki/XWPFConverterPDFViaIText#limitations
